/**
 * Admin Search Index — Central registry of all searchable admin sections & settings.
 *
 * Each entry contains rich metadata for intelligent matching:
 * - `name`        : Display name shown in search results
 * - `description` : Short human-readable description
 * - `route`       : Actual TanStack Router path (must exist)
 * - `breadcrumb`  : Visual location hierarchy in the admin panel
 * - `keywords`    : Primary terms for matching (exact/partial)
 * - `synonyms`    : Alternative terms, natural-language phrases, common typos
 * - `priority`    : 1–10 (higher = shown first in Quick Access & tie-breaking)
 * - `category`    : Grouping label (core / cms)
 *
 * To add a new searchable item, simply append an entry to the `SEARCH_INDEX` array.
 */

export interface SearchEntry {
  id: string;
  name: string;
  description: string;
  route: string;
  breadcrumb: string;
  keywords: string[];
  synonyms: string[];
  priority: number;
  category: "core" | "cms";
}

export const SEARCH_INDEX: SearchEntry[] = [
  // ═══════════════════════════════════════════════════════
  //  CORE — Operations & Management
  // ═══════════════════════════════════════════════════════
  {
    id: "dashboard",
    name: "Dashboard",
    description: "Overview of revenue, orders, products, and customers",
    route: "/admin",
    breadcrumb: "Admin → Dashboard",
    keywords: ["dashboard", "home", "overview", "stats", "summary"],
    synonyms: ["main page", "admin home", "control panel", "statistics", "revenue", "sales overview"],
    priority: 10,
    category: "core",
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "View sales analytics, trends, and performance metrics",
    route: "/admin/analytics",
    breadcrumb: "Admin → Analytics",
    keywords: ["analytics", "stats", "metrics", "data", "reports"],
    synonyms: ["sales data", "performance", "trends", "graphs", "charts", "insights", "reporting"],
    priority: 7,
    category: "core",
  },
  {
    id: "products",
    name: "Products",
    description: "Manage all products in your store",
    route: "/admin/products",
    breadcrumb: "Admin → Products",
    keywords: ["products", "items", "merchandise", "catalog"],
    synonyms: ["product list", "all products", "manage items", "product management", "store items", "add product"],
    priority: 9,
    category: "core",
  },
  {
    id: "inventory",
    name: "Inventory",
    description: "Track stock levels and manage product inventory",
    route: "/admin/inventory",
    breadcrumb: "Admin → Inventory",
    keywords: ["inventory", "stock", "quantity", "warehouse"],
    synonyms: ["stock management", "stock levels", "product stock", "available quantity", "out of stock", "restock"],
    priority: 8,
    category: "core",
  },
  {
    id: "catalog",
    name: "Catalog",
    description: "Manage product categories and collections",
    route: "/admin/catalog",
    breadcrumb: "Admin → Catalog",
    keywords: ["catalog", "categories", "collections", "tags"],
    synonyms: ["product categories", "category management", "organize products", "collections management"],
    priority: 7,
    category: "core",
  },
  {
    id: "sizes",
    name: "Sizes",
    description: "Configure available product sizes and size charts",
    route: "/admin/sizes",
    breadcrumb: "Admin → Sizes",
    keywords: ["sizes", "size chart", "measurements", "dimensions"],
    synonyms: ["size guide", "product sizes", "size options", "size management", "S M L XL", "fit guide"],
    priority: 6,
    category: "core",
  },
  {
    id: "orders",
    name: "Orders",
    description: "View and manage customer orders",
    route: "/admin/orders",
    breadcrumb: "Admin → Orders",
    keywords: ["orders", "purchases", "transactions", "order management"],
    synonyms: ["customer orders", "sales orders", "order list", "order status", "order tracking", "new orders"],
    priority: 9,
    category: "core",
  },
  {
    id: "invoices",
    name: "Invoices",
    description: "View and manage order invoices",
    route: "/admin/invoices",
    breadcrumb: "Admin → Invoices",
    keywords: ["invoices", "bills", "billing", "receipts"],
    synonyms: ["invoice list", "order invoices", "billing documents", "payment records"],
    priority: 5,
    category: "core",
  },
  {
    id: "invoice-template",
    name: "Invoice Template",
    description: "Customize the invoice template design and layout",
    route: "/admin/invoice-template",
    breadcrumb: "Admin → Invoice Template",
    keywords: ["invoice template", "invoice design", "invoice layout", "bill format"],
    synonyms: ["customize invoice", "invoice format", "billing template", "receipt template", "invoice branding"],
    priority: 4,
    category: "core",
  },
  {
    id: "refunds",
    name: "Refunds & Cancellations",
    description: "Process refunds and manage order cancellations",
    route: "/admin/refunds",
    breadcrumb: "Admin → Refunds",
    keywords: ["refunds", "cancellations", "refund", "cancel"],
    synonyms: ["process refund", "cancel order", "money back", "refund request", "order cancellation"],
    priority: 6,
    category: "core",
  },
  {
    id: "returns",
    name: "Returns",
    description: "Manage product return requests from customers",
    route: "/admin/returns",
    breadcrumb: "Admin → Returns",
    keywords: ["returns", "return requests", "exchanges"],
    synonyms: ["product returns", "return management", "exchange request", "return policy", "send back"],
    priority: 6,
    category: "core",
  },
  {
    id: "customers",
    name: "Customers",
    description: "View and manage registered customer accounts",
    route: "/admin/customers",
    breadcrumb: "Admin → Customers",
    keywords: ["customers", "users", "accounts", "buyers"],
    synonyms: ["customer list", "user management", "registered users", "customer accounts", "client list"],
    priority: 7,
    category: "core",
  },
  {
    id: "loyalty",
    name: "Loyalty",
    description: "Manage loyalty program tiers, points, and rewards",
    route: "/admin/loyalty",
    breadcrumb: "Admin → Loyalty",
    keywords: ["loyalty", "rewards", "points", "tiers"],
    synonyms: ["loyalty program", "reward points", "loyalty tiers", "customer loyalty", "earn points", "loyalty rewards"],
    priority: 6,
    category: "core",
  },
  {
    id: "export",
    name: "Export",
    description: "Export orders, products, and customer data",
    route: "/admin/export",
    breadcrumb: "Admin → Export",
    keywords: ["export", "download", "csv", "data export"],
    synonyms: ["export data", "download data", "export csv", "download orders", "backup data", "export products"],
    priority: 5,
    category: "core",
  },
  {
    id: "settings",
    name: "Settings",
    description: "Configure loyalty, brand, theme, shop, and payment options",
    route: "/admin/settings",
    breadcrumb: "Admin → Settings",
    keywords: ["settings", "configuration", "preferences", "options"],
    synonyms: ["admin settings", "general settings", "site settings", "store settings", "configure"],
    priority: 8,
    category: "core",
  },

  // Settings sub-sections (same route, different context)
  {
    id: "settings-brand",
    name: "Brand Settings",
    description: "Configure brand name, logo, and brand identity",
    route: "/admin/settings",
    breadcrumb: "Admin → Settings → Brand",
    keywords: ["brand", "logo", "brand name", "brand settings", "identity"],
    synonyms: ["brand identity", "store name", "company logo", "brand logo", "branding", "business name"],
    priority: 7,
    category: "core",
  },
  {
    id: "settings-theme",
    name: "Theme Settings",
    description: "Customize colors, typography, and visual appearance",
    route: "/admin/settings",
    breadcrumb: "Admin → Settings → Theme",
    keywords: ["theme", "colors", "typography", "appearance", "design"],
    synonyms: ["theme customization", "color scheme", "visual design", "site appearance", "look and feel", "dark mode", "light mode"],
    priority: 7,
    category: "core",
  },
  {
    id: "settings-shop",
    name: "Shop Settings",
    description: "Configure shop display and product listing options",
    route: "/admin/settings",
    breadcrumb: "Admin → Settings → Shop",
    keywords: ["shop", "store", "shop settings", "store settings"],
    synonyms: ["shop configuration", "store display", "product display", "shop options"],
    priority: 5,
    category: "core",
  },
  {
    id: "settings-cod",
    name: "Cash on Delivery",
    description: "Enable or configure cash on delivery payment option",
    route: "/admin/settings",
    breadcrumb: "Admin → Settings → COD",
    keywords: ["cod", "cash on delivery", "payment", "pay on delivery"],
    synonyms: ["COD settings", "cash payment", "delivery payment", "payment method", "pay later"],
    priority: 5,
    category: "core",
  },

  // ═══════════════════════════════════════════════════════
  //  CMS — Content & Customization
  // ═══════════════════════════════════════════════════════
  {
    id: "announcements",
    name: "Announcements",
    description: "Manage announcement banners and marquee messages",
    route: "/admin/announcements",
    breadcrumb: "CMS → Announcements",
    keywords: ["announcements", "banner", "marquee", "notice", "alert"],
    synonyms: ["announcement bar", "top bar", "notification bar", "site banner", "promo banner", "announcement banner", "marquee text", "scrolling text"],
    priority: 7,
    category: "cms",
  },
  {
    id: "website-sections",
    name: "Website Sections",
    description: "Manage homepage sections: hero, marquee, arrivals, and more",
    route: "/admin/website-sections",
    breadcrumb: "CMS → Website Sections",
    keywords: ["sections", "website sections", "homepage", "page sections", "layout"],
    synonyms: ["home page", "landing page", "page builder", "section order", "homepage layout", "site sections", "content sections"],
    priority: 9,
    category: "cms",
  },
  {
    id: "website-sections-hero",
    name: "Hero Section",
    description: "Edit the main hero banner slides, images, and CTAs",
    route: "/admin/website-sections",
    breadcrumb: "CMS → Website Sections → Hero",
    keywords: ["hero", "hero banner", "hero slides", "main banner", "slider"],
    synonyms: ["homepage banner", "main slider", "hero image", "landing banner", "top banner", "hero video", "banner slides"],
    priority: 8,
    category: "cms",
  },
  {
    id: "mega-menu",
    name: "Mega Menu",
    description: "Configure the navigation mega menu categories and links",
    route: "/admin/mega-menu",
    breadcrumb: "CMS → Mega Menu",
    keywords: ["mega menu", "megamenu", "navigation", "nav menu", "header menu"],
    synonyms: ["main menu", "header navigation", "site menu", "navigation bar", "navbar menu", "menu categories", "dropdown menu"],
    priority: 8,
    category: "cms",
  },
  {
    id: "footer-links",
    name: "Footer Links",
    description: "Manage links displayed in the website footer",
    route: "/admin/navigation",
    breadcrumb: "CMS → Footer Links",
    keywords: ["footer", "footer links", "bottom links", "footer navigation"],
    synonyms: ["footer menu", "footer nav", "bottom navigation", "website footer", "footer columns", "footer sections", "fotter"],
    priority: 7,
    category: "cms",
  },
  {
    id: "faq",
    name: "FAQ",
    description: "Manage frequently asked questions and answers",
    route: "/admin/faq",
    breadcrumb: "CMS → FAQ",
    keywords: ["faq", "questions", "answers", "help", "support"],
    synonyms: ["frequently asked questions", "help center", "Q&A", "common questions", "help page"],
    priority: 6,
    category: "cms",
  },
  {
    id: "testimonials",
    name: "Testimonials",
    description: "Manage customer reviews and testimonial quotes",
    route: "/admin/testimonials",
    breadcrumb: "CMS → Testimonials",
    keywords: ["testimonials", "reviews", "quotes", "feedback"],
    synonyms: ["customer reviews", "customer feedback", "review management", "user testimonials", "social proof", "ratings"],
    priority: 6,
    category: "cms",
  },
  {
    id: "influencer-picks",
    name: "Influencer Picks",
    description: "Manage influencer curated product picks and profiles",
    route: "/admin/influencer-picks",
    breadcrumb: "CMS → Influencers",
    keywords: ["influencers", "influencer picks", "creators", "ambassadors"],
    synonyms: ["influencer products", "creator picks", "brand ambassadors", "influencer marketing", "celebrity picks", "content creators"],
    priority: 5,
    category: "cms",
  },
  {
    id: "lookbook",
    name: "Look Book",
    description: "Curate lookbook slides with product links",
    route: "/admin/lookbook-cms",
    breadcrumb: "CMS → Look Book",
    keywords: ["lookbook", "look book", "editorial", "styled looks"],
    synonyms: ["lookbook slides", "fashion editorial", "outfit cards", "style gallery", "curated looks", "lookbook carousel"],
    priority: 6,
    category: "cms",
  },
  {
    id: "community",
    name: "Community",
    description: "Manage community content and user-generated posts",
    route: "/admin/community-cms",
    breadcrumb: "CMS → Community",
    keywords: ["community", "ugc", "user content", "social"],
    synonyms: ["community posts", "user generated content", "social wall", "community gallery", "customer photos"],
    priority: 5,
    category: "cms",
  },
  {
    id: "headings",
    name: "Headings",
    description: "Customize section headings and titles across the website",
    route: "/admin/headings",
    breadcrumb: "CMS → Headings",
    keywords: ["headings", "titles", "section titles", "heading text"],
    synonyms: ["section headings", "page titles", "heading customization", "title text", "change titles", "rename sections"],
    priority: 5,
    category: "cms",
  },
  {
    id: "preloader",
    name: "Preloader",
    description: "Customize the website loading screen animation",
    route: "/admin/preloader",
    breadcrumb: "CMS → Preloader",
    keywords: ["preloader", "loader", "loading", "splash screen", "loading screen"],
    synonyms: ["loading animation", "loading screen", "splash page", "intro animation", "website loader", "page loader", "loading effect", "startup screen", "launch screen"],
    priority: 7,
    category: "cms",
  },
  {
    id: "popup",
    name: "Popup",
    description: "Configure promotional popup overlays and modals",
    route: "/admin/popup",
    breadcrumb: "CMS → Popup",
    keywords: ["popup", "modal", "overlay", "promo popup", "pop up"],
    synonyms: ["popup banner", "promotional popup", "popup modal", "site popup", "popup settings", "popup design", "popup image", "welcome popup", "discount popup"],
    priority: 7,
    category: "cms",
  },
  {
    id: "media",
    name: "Media Library",
    description: "Upload and manage images, videos, and media assets",
    route: "/admin/media",
    breadcrumb: "CMS → Media",
    keywords: ["media", "images", "videos", "uploads", "gallery", "assets"],
    synonyms: ["media library", "image upload", "video upload", "file manager", "asset management", "photo library", "media manager"],
    priority: 6,
    category: "cms",
  },
  {
    id: "seo",
    name: "SEO Settings",
    description: "Manage page titles, meta descriptions, and SEO tags",
    route: "/admin/seo",
    breadcrumb: "CMS → SEO",
    keywords: ["seo", "meta", "title tags", "meta description", "search engine"],
    synonyms: ["search engine optimization", "page titles", "meta tags", "google ranking", "search visibility", "seo management", "seo tags", "page meta"],
    priority: 7,
    category: "cms",
  },
  {
    id: "whatsapp",
    name: "WhatsApp Notifications",
    description: "Configure WhatsApp message templates and notifications",
    route: "/admin/notifications",
    breadcrumb: "CMS → WhatsApp",
    keywords: ["whatsapp", "notifications", "messages", "messaging"],
    synonyms: ["whatsapp messages", "order notifications", "whatsapp templates", "message templates", "whatsapp integration", "customer notifications", "sms"],
    priority: 6,
    category: "cms",
  },
  {
    id: "users",
    name: "Users",
    description: "Manage admin users and access permissions",
    route: "/admin/users",
    breadcrumb: "CMS → Users",
    keywords: ["users", "admin users", "permissions", "access", "roles"],
    synonyms: ["user management", "admin access", "user roles", "team members", "admin permissions", "staff management"],
    priority: 5,
    category: "cms",
  },
];

/**
 * Returns the top N entries sorted by priority (highest first).
 * Used for the Quick Access state when the search bar is focused but empty.
 */
export function getQuickAccessItems(count = 6): SearchEntry[] {
  return [...SEARCH_INDEX]
    .sort((a, b) => b.priority - a.priority)
    .slice(0, count);
}
