/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AdminWebsiteSectionsRouteImport } from './routes/admin.website-sections'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoyaltyRouteImport } from './routes/admin.loyalty'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminInvoiceTemplateRouteImport } from './routes/admin.invoice-template'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminArrivalsRouteImport } from './routes/admin.arrivals'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsSlugRouteImport } from './routes/admin.products.$slug'
import { Route as AdminInvoiceIdRouteImport } from './routes/admin.invoice.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteSectionsRoute = AdminWebsiteSectionsRouteImport.update({
  id: '/website-sections',
  path: '/website-sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoiceTemplateRoute = AdminInvoiceTemplateRouteImport.update({
  id: '/invoice-template',
  path: '/invoice-template',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArrivalsRoute = AdminArrivalsRouteImport.update({
  id: '/arrivals',
  path: '/arrivals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsSlugRoute = AdminProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminInvoiceIdRoute = AdminInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/policies': typeof PoliciesRoute
  '/refer': typeof ReferRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/size-guide': typeof SizeGuideRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/arrivals': typeof AdminArrivalsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/invoice-template': typeof AdminInvoiceTemplateRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website-sections': typeof AdminWebsiteSectionsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/invoice/$id': typeof AdminInvoiceIdRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/policies': typeof PoliciesRoute
  '/refer': typeof ReferRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/size-guide': typeof SizeGuideRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/arrivals': typeof AdminArrivalsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/invoice-template': typeof AdminInvoiceTemplateRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website-sections': typeof AdminWebsiteSectionsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/invoice/$id': typeof AdminInvoiceIdRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/policies': typeof PoliciesRoute
  '/refer': typeof ReferRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/size-guide': typeof SizeGuideRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/arrivals': typeof AdminArrivalsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/invoice-template': typeof AdminInvoiceTemplateRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website-sections': typeof AdminWebsiteSectionsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/invoice/$id': typeof AdminInvoiceIdRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/lookbook'
    | '/policies'
    | '/refer'
    | '/rewards'
    | '/shop'
    | '/signup'
    | '/size-guide'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/arrivals'
    | '/admin/catalog'
    | '/admin/customers'
    | '/admin/export'
    | '/admin/faq'
    | '/admin/invoice-template'
    | '/admin/invoices'
    | '/admin/loyalty'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/website-sections'
    | '/collections/$slug'
    | '/invoice/$id'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/invoice/$id'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/lookbook'
    | '/policies'
    | '/refer'
    | '/rewards'
    | '/shop'
    | '/signup'
    | '/size-guide'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/arrivals'
    | '/admin/catalog'
    | '/admin/customers'
    | '/admin/export'
    | '/admin/faq'
    | '/admin/invoice-template'
    | '/admin/invoices'
    | '/admin/loyalty'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/refunds'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/website-sections'
    | '/collections/$slug'
    | '/invoice/$id'
    | '/order/$id'
    | '/product/$slug'
    | '/admin'
    | '/admin/invoice/$id'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/lookbook'
    | '/policies'
    | '/refer'
    | '/rewards'
    | '/shop'
    | '/signup'
    | '/size-guide'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/arrivals'
    | '/admin/catalog'
    | '/admin/customers'
    | '/admin/export'
    | '/admin/faq'
    | '/admin/invoice-template'
    | '/admin/invoices'
    | '/admin/loyalty'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/website-sections'
    | '/collections/$slug'
    | '/invoice/$id'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/invoice/$id'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  LookbookRoute: typeof LookbookRoute
  PoliciesRoute: typeof PoliciesRoute
  ReferRoute: typeof ReferRoute
  RewardsRoute: typeof RewardsRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  SizeGuideRoute: typeof SizeGuideRoute
  WishlistRoute: typeof WishlistRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website-sections': {
      id: '/admin/website-sections'
      path: '/website-sections'
      fullPath: '/admin/website-sections'
      preLoaderRoute: typeof AdminWebsiteSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoice-template': {
      id: '/admin/invoice-template'
      path: '/invoice-template'
      fullPath: '/admin/invoice-template'
      preLoaderRoute: typeof AdminInvoiceTemplateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arrivals': {
      id: '/admin/arrivals'
      path: '/arrivals'
      fullPath: '/admin/arrivals'
      preLoaderRoute: typeof AdminArrivalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$slug': {
      id: '/admin/products/$slug'
      path: '/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AdminProductsSlugRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/invoice/$id': {
      id: '/admin/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/admin/invoice/$id'
      preLoaderRoute: typeof AdminInvoiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsSlugRoute: typeof AdminProductsSlugRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsSlugRoute: AdminProductsSlugRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminArrivalsRoute: typeof AdminArrivalsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminInvoiceTemplateRoute: typeof AdminInvoiceTemplateRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebsiteSectionsRoute: typeof AdminWebsiteSectionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInvoiceIdRoute: typeof AdminInvoiceIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminArrivalsRoute: AdminArrivalsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminExportRoute: AdminExportRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminInvoiceTemplateRoute: AdminInvoiceTemplateRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebsiteSectionsRoute: AdminWebsiteSectionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInvoiceIdRoute: AdminInvoiceIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  LookbookRoute: LookbookRoute,
  PoliciesRoute: PoliciesRoute,
  ReferRoute: ReferRoute,
  RewardsRoute: RewardsRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  SizeGuideRoute: SizeGuideRoute,
  WishlistRoute: WishlistRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
