/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollaboratorsRouteImport } from './routes/collaborators'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CouriersRouteImport } from './routes/couriers'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminCommunityCmsRouteImport } from './routes/admin.community-cms'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminHeadingsRouteImport } from './routes/admin.headings'
import { Route as AdminInfluencerPicksRouteImport } from './routes/admin.influencer-picks'
import { Route as AdminInvoiceTemplateRouteImport } from './routes/admin.invoice-template'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminLookbookCmsRouteImport } from './routes/admin.lookbook-cms'
import { Route as AdminLoyaltyRouteImport } from './routes/admin.loyalty'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMegaMenuRouteImport } from './routes/admin.mega-menu'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPopupRouteImport } from './routes/admin.popup'
import { Route as AdminPreloaderRouteImport } from './routes/admin.preloader'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminReturnsRouteImport } from './routes/admin.returns'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSizesRouteImport } from './routes/admin.sizes'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWebsiteSectionsRouteImport } from './routes/admin.website-sections'
import { Route as CollaboratorsArtRouteImport } from './routes/collaborators.art'
import { Route as CollaboratorsDanceRouteImport } from './routes/collaborators.dance'
import { Route as CollaboratorsInfluencersRouteImport } from './routes/collaborators.influencers'
import { Route as CollaboratorsModelsRouteImport } from './routes/collaborators.models'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminInvoiceIdRouteImport } from './routes/admin.invoice.$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsSlugRouteImport } from './routes/admin.products.$slug'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaboratorsRoute = CollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CouriersRoute = CouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityCmsRoute = AdminCommunityCmsRouteImport.update({
  id: '/community-cms',
  path: '/community-cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeadingsRoute = AdminHeadingsRouteImport.update({
  id: '/headings',
  path: '/headings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfluencerPicksRoute = AdminInfluencerPicksRouteImport.update({
  id: '/influencer-picks',
  path: '/influencer-picks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoiceTemplateRoute = AdminInvoiceTemplateRouteImport.update({
  id: '/invoice-template',
  path: '/invoice-template',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLookbookCmsRoute = AdminLookbookCmsRouteImport.update({
  id: '/lookbook-cms',
  path: '/lookbook-cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMegaMenuRoute = AdminMegaMenuRouteImport.update({
  id: '/mega-menu',
  path: '/mega-menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopupRoute = AdminPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreloaderRoute = AdminPreloaderRouteImport.update({
  id: '/preloader',
  path: '/preloader',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSizesRoute = AdminSizesRouteImport.update({
  id: '/sizes',
  path: '/sizes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteSectionsRoute = AdminWebsiteSectionsRouteImport.update({
  id: '/website-sections',
  path: '/website-sections',
  getParentRoute: () => AdminRoute,
} as any)
const CollaboratorsArtRoute = CollaboratorsArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => CollaboratorsRoute,
} as any)
const CollaboratorsDanceRoute = CollaboratorsDanceRouteImport.update({
  id: '/dance',
  path: '/dance',
  getParentRoute: () => CollaboratorsRoute,
} as any)
const CollaboratorsInfluencersRoute =
  CollaboratorsInfluencersRouteImport.update({
    id: '/influencers',
    path: '/influencers',
    getParentRoute: () => CollaboratorsRoute,
  } as any)
const CollaboratorsModelsRoute = CollaboratorsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => CollaboratorsRoute,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoiceIdRoute = AdminInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsSlugRoute = AdminProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collaborators': typeof CollaboratorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/couriers': typeof CouriersRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/refer': typeof ReferRoute
  '/returns': typeof ReturnsRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/community-cms': typeof AdminCommunityCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/headings': typeof AdminHeadingsRoute
  '/admin/influencer-picks': typeof AdminInfluencerPicksRoute
  '/admin/invoice-template': typeof AdminInvoiceTemplateRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/lookbook-cms': typeof AdminLookbookCmsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/mega-menu': typeof AdminMegaMenuRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/preloader': typeof AdminPreloaderRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sizes': typeof AdminSizesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website-sections': typeof AdminWebsiteSectionsRoute
  '/collaborators/art': typeof CollaboratorsArtRoute
  '/collaborators/dance': typeof CollaboratorsDanceRoute
  '/collaborators/influencers': typeof CollaboratorsInfluencersRoute
  '/collaborators/models': typeof CollaboratorsModelsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/invoice/$id': typeof AdminInvoiceIdRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collaborators': typeof CollaboratorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/couriers': typeof CouriersRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/refer': typeof ReferRoute
  '/returns': typeof ReturnsRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/community-cms': typeof AdminCommunityCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/headings': typeof AdminHeadingsRoute
  '/admin/influencer-picks': typeof AdminInfluencerPicksRoute
  '/admin/invoice-template': typeof AdminInvoiceTemplateRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/lookbook-cms': typeof AdminLookbookCmsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/mega-menu': typeof AdminMegaMenuRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/preloader': typeof AdminPreloaderRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sizes': typeof AdminSizesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website-sections': typeof AdminWebsiteSectionsRoute
  '/collaborators/art': typeof CollaboratorsArtRoute
  '/collaborators/dance': typeof CollaboratorsDanceRoute
  '/collaborators/influencers': typeof CollaboratorsInfluencersRoute
  '/collaborators/models': typeof CollaboratorsModelsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/invoice/$id': typeof AdminInvoiceIdRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collaborators': typeof CollaboratorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/couriers': typeof CouriersRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/refer': typeof ReferRoute
  '/returns': typeof ReturnsRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/community-cms': typeof AdminCommunityCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/headings': typeof AdminHeadingsRoute
  '/admin/influencer-picks': typeof AdminInfluencerPicksRoute
  '/admin/invoice-template': typeof AdminInvoiceTemplateRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/lookbook-cms': typeof AdminLookbookCmsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/mega-menu': typeof AdminMegaMenuRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/preloader': typeof AdminPreloaderRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sizes': typeof AdminSizesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website-sections': typeof AdminWebsiteSectionsRoute
  '/collaborators/art': typeof CollaboratorsArtRoute
  '/collaborators/dance': typeof CollaboratorsDanceRoute
  '/collaborators/influencers': typeof CollaboratorsInfluencersRoute
  '/collaborators/models': typeof CollaboratorsModelsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/invoice/$id': typeof AdminInvoiceIdRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/collaborators'
    | '/contact'
    | '/couriers'
    | '/faq'
    | '/login'
    | '/lookbook'
    | '/policies'
    | '/privacy'
    | '/refer'
    | '/returns'
    | '/rewards'
    | '/shop'
    | '/signup'
    | '/size-guide'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/catalog'
    | '/admin/community-cms'
    | '/admin/customers'
    | '/admin/export'
    | '/admin/faq'
    | '/admin/headings'
    | '/admin/influencer-picks'
    | '/admin/invoice-template'
    | '/admin/invoices'
    | '/admin/lookbook-cms'
    | '/admin/loyalty'
    | '/admin/media'
    | '/admin/mega-menu'
    | '/admin/navigation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/popup'
    | '/admin/preloader'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/returns'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/sizes'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/website-sections'
    | '/collaborators/art'
    | '/collaborators/dance'
    | '/collaborators/influencers'
    | '/collaborators/models'
    | '/collections/$slug'
    | '/invoice/$id'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/invoice/$id'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/collaborators'
    | '/contact'
    | '/couriers'
    | '/faq'
    | '/login'
    | '/lookbook'
    | '/policies'
    | '/privacy'
    | '/refer'
    | '/returns'
    | '/rewards'
    | '/shop'
    | '/signup'
    | '/size-guide'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/catalog'
    | '/admin/community-cms'
    | '/admin/customers'
    | '/admin/export'
    | '/admin/faq'
    | '/admin/headings'
    | '/admin/influencer-picks'
    | '/admin/invoice-template'
    | '/admin/invoices'
    | '/admin/lookbook-cms'
    | '/admin/loyalty'
    | '/admin/media'
    | '/admin/mega-menu'
    | '/admin/navigation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/popup'
    | '/admin/preloader'
    | '/admin/refunds'
    | '/admin/returns'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/sizes'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/website-sections'
    | '/collaborators/art'
    | '/collaborators/dance'
    | '/collaborators/influencers'
    | '/collaborators/models'
    | '/collections/$slug'
    | '/invoice/$id'
    | '/order/$id'
    | '/product/$slug'
    | '/admin'
    | '/admin/invoice/$id'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/collaborators'
    | '/contact'
    | '/couriers'
    | '/faq'
    | '/login'
    | '/lookbook'
    | '/policies'
    | '/privacy'
    | '/refer'
    | '/returns'
    | '/rewards'
    | '/shop'
    | '/signup'
    | '/size-guide'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/catalog'
    | '/admin/community-cms'
    | '/admin/customers'
    | '/admin/export'
    | '/admin/faq'
    | '/admin/headings'
    | '/admin/influencer-picks'
    | '/admin/invoice-template'
    | '/admin/invoices'
    | '/admin/lookbook-cms'
    | '/admin/loyalty'
    | '/admin/media'
    | '/admin/mega-menu'
    | '/admin/navigation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/popup'
    | '/admin/preloader'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/returns'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/sizes'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/website-sections'
    | '/collaborators/art'
    | '/collaborators/dance'
    | '/collaborators/influencers'
    | '/collaborators/models'
    | '/collections/$slug'
    | '/invoice/$id'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/invoice/$id'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollaboratorsRoute: typeof CollaboratorsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CouriersRoute: typeof CouriersRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  LookbookRoute: typeof LookbookRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferRoute: typeof ReferRoute
  ReturnsRoute: typeof ReturnsRoute
  RewardsRoute: typeof RewardsRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  SizeGuideRoute: typeof SizeGuideRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborators': {
      id: '/collaborators'
      path: '/collaborators'
      fullPath: '/collaborators'
      preLoaderRoute: typeof CollaboratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couriers': {
      id: '/couriers'
      path: '/couriers'
      fullPath: '/couriers'
      preLoaderRoute: typeof CouriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community-cms': {
      id: '/admin/community-cms'
      path: '/community-cms'
      fullPath: '/admin/community-cms'
      preLoaderRoute: typeof AdminCommunityCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/headings': {
      id: '/admin/headings'
      path: '/headings'
      fullPath: '/admin/headings'
      preLoaderRoute: typeof AdminHeadingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/influencer-picks': {
      id: '/admin/influencer-picks'
      path: '/influencer-picks'
      fullPath: '/admin/influencer-picks'
      preLoaderRoute: typeof AdminInfluencerPicksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoice-template': {
      id: '/admin/invoice-template'
      path: '/invoice-template'
      fullPath: '/admin/invoice-template'
      preLoaderRoute: typeof AdminInvoiceTemplateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lookbook-cms': {
      id: '/admin/lookbook-cms'
      path: '/lookbook-cms'
      fullPath: '/admin/lookbook-cms'
      preLoaderRoute: typeof AdminLookbookCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mega-menu': {
      id: '/admin/mega-menu'
      path: '/mega-menu'
      fullPath: '/admin/mega-menu'
      preLoaderRoute: typeof AdminMegaMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popup': {
      id: '/admin/popup'
      path: '/popup'
      fullPath: '/admin/popup'
      preLoaderRoute: typeof AdminPopupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preloader': {
      id: '/admin/preloader'
      path: '/preloader'
      fullPath: '/admin/preloader'
      preLoaderRoute: typeof AdminPreloaderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sizes': {
      id: '/admin/sizes'
      path: '/sizes'
      fullPath: '/admin/sizes'
      preLoaderRoute: typeof AdminSizesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website-sections': {
      id: '/admin/website-sections'
      path: '/website-sections'
      fullPath: '/admin/website-sections'
      preLoaderRoute: typeof AdminWebsiteSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/collaborators/art': {
      id: '/collaborators/art'
      path: '/art'
      fullPath: '/collaborators/art'
      preLoaderRoute: typeof CollaboratorsArtRouteImport
      parentRoute: typeof CollaboratorsRoute
    }
    '/collaborators/dance': {
      id: '/collaborators/dance'
      path: '/dance'
      fullPath: '/collaborators/dance'
      preLoaderRoute: typeof CollaboratorsDanceRouteImport
      parentRoute: typeof CollaboratorsRoute
    }
    '/collaborators/influencers': {
      id: '/collaborators/influencers'
      path: '/influencers'
      fullPath: '/collaborators/influencers'
      preLoaderRoute: typeof CollaboratorsInfluencersRouteImport
      parentRoute: typeof CollaboratorsRoute
    }
    '/collaborators/models': {
      id: '/collaborators/models'
      path: '/models'
      fullPath: '/collaborators/models'
      preLoaderRoute: typeof CollaboratorsModelsRouteImport
      parentRoute: typeof CollaboratorsRoute
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoice/$id': {
      id: '/admin/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/admin/invoice/$id'
      preLoaderRoute: typeof AdminInvoiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$slug': {
      id: '/admin/products/$slug'
      path: '/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AdminProductsSlugRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsSlugRoute: typeof AdminProductsSlugRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsSlugRoute: AdminProductsSlugRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCommunityCmsRoute: typeof AdminCommunityCmsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminHeadingsRoute: typeof AdminHeadingsRoute
  AdminInfluencerPicksRoute: typeof AdminInfluencerPicksRoute
  AdminInvoiceTemplateRoute: typeof AdminInvoiceTemplateRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLookbookCmsRoute: typeof AdminLookbookCmsRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMegaMenuRoute: typeof AdminMegaMenuRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPopupRoute: typeof AdminPopupRoute
  AdminPreloaderRoute: typeof AdminPreloaderRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSizesRoute: typeof AdminSizesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebsiteSectionsRoute: typeof AdminWebsiteSectionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInvoiceIdRoute: typeof AdminInvoiceIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCommunityCmsRoute: AdminCommunityCmsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminExportRoute: AdminExportRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminHeadingsRoute: AdminHeadingsRoute,
  AdminInfluencerPicksRoute: AdminInfluencerPicksRoute,
  AdminInvoiceTemplateRoute: AdminInvoiceTemplateRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLookbookCmsRoute: AdminLookbookCmsRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMegaMenuRoute: AdminMegaMenuRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPopupRoute: AdminPopupRoute,
  AdminPreloaderRoute: AdminPreloaderRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSizesRoute: AdminSizesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebsiteSectionsRoute: AdminWebsiteSectionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInvoiceIdRoute: AdminInvoiceIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CollaboratorsRouteChildren {
  CollaboratorsArtRoute: typeof CollaboratorsArtRoute
  CollaboratorsDanceRoute: typeof CollaboratorsDanceRoute
  CollaboratorsInfluencersRoute: typeof CollaboratorsInfluencersRoute
  CollaboratorsModelsRoute: typeof CollaboratorsModelsRoute
}

const CollaboratorsRouteChildren: CollaboratorsRouteChildren = {
  CollaboratorsArtRoute: CollaboratorsArtRoute,
  CollaboratorsDanceRoute: CollaboratorsDanceRoute,
  CollaboratorsInfluencersRoute: CollaboratorsInfluencersRoute,
  CollaboratorsModelsRoute: CollaboratorsModelsRoute,
}

const CollaboratorsRouteWithChildren = CollaboratorsRoute._addFileChildren(
  CollaboratorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollaboratorsRoute: CollaboratorsRouteWithChildren,
  ContactRoute: ContactRoute,
  CouriersRoute: CouriersRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  LookbookRoute: LookbookRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyRoute: PrivacyRoute,
  ReferRoute: ReferRoute,
  ReturnsRoute: ReturnsRoute,
  RewardsRoute: RewardsRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  SizeGuideRoute: SizeGuideRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
